import type { PayloadAction } from "@reduxjs/toolkit";
import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import { AuthenticationResponse } from "./AuthenticationResponse";
import { doValidateSession } from "./SessionAPI";
import SessionInfo from "./SessionInfo";

// Define the TS type for the counter slice's state
export interface SessionState {
    authenticated: boolean,
    status: "authenticating" | "idle" | "failed"
}

// Define the initial value for the slice state
const initialState: SessionState = {
    authenticated: false,
    status: "idle"
};

// Slices contain Redux reducer logic for updating state, and
// generate actions that can be dispatched to trigger those updates.
export const SessionSlice = createSlice({
    name: "session",
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
        // Use the PayloadAction type to declare the contents of `action.payload`
        validateSession: (state, action: PayloadAction<AuthenticationResponse>) => {
            state.authenticated = action.payload.getAuthenticated();
        }
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: builder => {
        builder
            // Handle the action types defined by the `incrementAsync` thunk defined below.
            // This lets the slice reducer update the state with request status and results.
            .addCase(doAsyncStub.pending, state => {
                state.status = "authenticating";
            })
            .addCase(doAsyncStub.fulfilled, (state, action) => {
                state.status = "idle";
                state.authenticated = action.payload.getAuthenticated();
            })
            .addCase(doAsyncStub.rejected, state => {
                state.status = "failed";
                state.authenticated = false;
            })
    },
    selectors: {
        selectCount: (state) => state.authenticated,
        selectStatus: (state) => state.status
    }
});

// Export the generated action creators for use in components
export const { validateSession } = SessionSlice.actions;

// Export the slice reducer for use in the store configuration
export const sessionReducer = SessionSlice.reducer;

// Selector functions allows us to select a value from the Redux root state.
// Selectors can also be defined inline in the `useSelector` call
// in a component, or inside the `createSlice.selectors` field.
export const selectCount = SessionSlice.selectors.selectCount;
export const selectStatus = SessionSlice.selectors.selectStatus;

// The function below is called a thunk, which can contain both sync and async logic
// that has access to both `dispatch` and `getState`. They can be dispatched like
// a regular action: `dispatch(incrementIfOdd(10))`.
// Here's an example of conditionally dispatching actions based on current state.
// export const incrementIfOdd = (amount: number): AppThunk => {
//     return (dispatch, getState) => {
//         const currentValue = selectCount(getState())
//         if (currentValue % 2 === 1) {
//             dispatch(validateSession(amount))
//         }
//     }
// };

// Thunks are commonly used for async logic like fetching data.
// The `createAsyncThunk` method is used to generate thunks that
// dispatch pending/fulfilled/rejected actions based on a promise.
// In this example, we make a mock async request and return the result.
// The `createSlice.extraReducers` field can handle these actions
// and update the state with the results.
export const doAsyncStub = createAsyncThunk(
    'session/validateSession',
    async (credentials: SessionInfo) => {
        const response = await doValidateSession(credentials);
        // The value we return becomes the `fulfilled` action payload
        return response.data;
    }
);
