import type { AppThunk } from "@/store";
import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import { uploadAttachment as doSaveNoteAsync } from "./EditorAPI";

// Define the TS type for the counter slice's state
export interface EditorState {
  value: string,
  status: "idle" | "loading" | "failed"
}

// Define the initial value for the slice state
const initialState: EditorState = {
  value: 'note...',
  status: "idle",
};

// Slices contain Redux reducer logic for updating state, and
// generate actions that can be dispatched to trigger those updates.
export const EditorSlice = createSlice({
  name: "editor",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    saveNote: state => {
      // Redux Toolkit allows us to write "mutating" logic in reducers. It
      // doesn't actually mutate the state because it uses the Immer library,
      // which detects changes to a "draft state" and produces a brand new
      // immutable state based off those changes
      state.value += 1;
    }
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: builder => {
    builder
      // Handle the action types defined by the `incrementAsync` thunk defined below.
      // This lets the slice reducer update the state with request status and results.
      .addCase(saveNoteAsync.pending, state => {
        state.status = "loading";
      })
      .addCase(saveNoteAsync.fulfilled, (state, action) => {
        state.status = "idle";
        state.value += action.payload;
      })
      .addCase(saveNoteAsync.rejected, state => {
        state.status = "failed";
      })
  },
  selectors: {
    selectCount: (state) => state.value,
    selectStatus: (state) => state.status
  }
});

// Export the generated action creators for use in components
export const { saveNote } = EditorSlice.actions;

// Export the slice reducer for use in the store configuration
export const editorReducer = EditorSlice.reducer;
export const selectCount = EditorSlice.selectors.selectCount;
export const selectStatus = EditorSlice.selectors.selectStatus;

// The function below is called a thunk, which can contain both sync and async logic
// that has access to both `dispatch` and `getState`. They can be dispatched like
// a regular action: `dispatch(incrementIfOdd(10))`.
// Here's an example of conditionally dispatching actions based on current state.
export const incrementIfOdd = (amount: number): AppThunk => {
  return (dispatch, getState) => {
    const currentValue = selectCount(getState());
    if (currentValue) {
      dispatch(saveNote());
    }
  }
};

// Thunks are commonly used for async logic like fetching data.
// The `createAsyncThunk` method is used to generate thunks that
// dispatch pending/fulfilled/rejected actions based on a promise.
// In this example, we make a mock async request and return the result.
// The `createSlice.extraReducers` field can handle these actions
// and update the state with the results.
export const saveNoteAsync = createAsyncThunk(
  "editor/saveNote",
  async (amount: number) => {
    const response = await doSaveNoteAsync(amount);
    // The value we return becomes the `fulfilled` action payload
    return response.data;
  }
);
